# Generated by Django 2.2.6 on 2019-12-16 01:55

from django.db import migrations, models
import django.utils.timezone
import geostuff_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('geostuff_app', '0002_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='step',
            name='type',
            field=models.IntegerField(choices=[(1, 'ACCOMMODATION'), (2, 'FOOD'), (3, 'POI')], default=geostuff_app.models.StepType(3)),
        ),
    ]
